# Generated by Django 4.2.7 on 2023-11-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', 'uzbek'), ('ru', 'russian'), ('en', 'english')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
